### ISSUE TITLE
有没有兴趣支持 trzsz ( trz / tsz ) ？一个类似 rz / sz 那样的文件传输工具。

### ISSUE THREAD

**Issue by lonnywong** [luanruisong/tssh#3]
go 版 trzsz 开源地址：https://github.com/trzsz/trzsz-go

在不直接支持 trzsz 的终端，打开本地 shell，然后`trzsz ssh x.x.x.x` 这样登录，就可以使用 `trz / tsz` 上传和下载了。

在 Windows Terminal 中，这种用法的上传速度很慢，我一直没想到解决办法。今晚我想到了，用 go 实现一个 ssh 客户端就可以了，至少在 Windows Terminal 登录 Linux 服务器是可以的。如果是登录 Windows 服务器，那估计还是很慢。

在我想给这个 ssh 客户端起个名字时，我首先想到了 tssh（ 取 trzsz 的首字母 t ），然后就搜到了这项目，正好也是用 go 写的，太棒了！

我看了下，这个 tssh 的功能也很棒👍。如果你愿意支持 trzsz，我抽空提个 PR 过来。

**Comment by luanruisong** [comment]
哦吼？正要开始摸鱼之际，居然还有这种好消息传来？
tssh 源于我在mac上面有这管理账户密码的需求而诞生，不想使用.ssh/config配置文件且对except脚本深恶痛绝，又不甘心使用现有的ssh GUI。
但是对于ssh客户端原本需要的技术，我认为我的储备是不够充足的。（这也是后续没有更多的更新主要原因之一）
其实我一直也在想要以什么方式对这个项目进行重构（比如另一个issues中提到的双因子认证），但是一直苦于相关知识不够扎实，迟迟没有什么进展。
首先欢迎老哥对于这个库有任何PR，这是我的荣幸，也是tssh的荣幸。
大家合力提供一个好用、耐用的工具，这也是我整理归纳自己repo的初衷。
ps：大佬带带弟弟
![](https://blog-img.luanruisong.com/blog/img/2022/202305220942974.png)

**Comment by lonnywong** [comment]
等下个周末我提个 PR 过来。

我喜欢密钥登录那一套，简单写了个自用 https://github.com/trzsz/trzsz-ssh ，功能还很不完善。不打算实现类似 tssh 这样的管理功能，只会读 ～/.ssh/config 这一个文件，后面有空会尽量做的更像 ssh 一些。

**Comment by lonnywong** [comment]
你要有空的话，也可以不用等我提 PR ，照 https://github.com/trzsz/trzsz-go/blob/main/examples/ssh_client.go 或 https://github.com/trzsz/trzsz-ssh/blob/main/tssh.go 抄一下就好。

**Comment by luanruisong** [comment]
准备观摩一下代码，其实我不太清楚要更新哪些东西，不过先看看总归没错的

**Comment by xuxin930** [comment]
hi@lonnywong , is there any plans to update Usage?
is there a latest version released, how should I use it

**Comment by lonnywong** [comment]
> hi@lonnywong , is there any plans to update Usage? is there a latest version released, how should I use it

@xuxin930 You can try https://github.com/trzsz/trzsz-ssh

**Comment by xuxin930** [comment]
> @xuxin930 You can try https://github.com/trzsz/trzsz-ssh
this is exactly what I want and, deserves a star✨
